# Generated by Django 6.0.5 on 2026-06-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('hash', 'Hash'), ('email', 'Email')], max_length=20)),
                ('value', models.CharField(max_length=500)),
                ('confidence', models.IntegerField(default=50)),
                ('source', models.CharField(max_length=100)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('related_threat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='threats.threat')),
            ],
            options={
                'ordering': ['-first_seen'],
                'unique_together': {('ioc_type', 'value')},
            },
        ),
    ]
