# Generated by Django 6.0.5 on 2026-06-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('exploit_available', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
